### ISSUE TITLE
dynamic constant assigment error

### ISSUE THREAD

**Issue by hiteshsharma** [kucaahbe/rspec-html-matchers#63]
Hi I get this error each time I run `bundle exec rspec`

```
/usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require': /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-html-matchers-0.7.3/lib/rspec-html-matchers.rb:280: syntax error, unexpected ':', expecting ')' (SyntaxError)
    have_tag(tag, options.merge(text: ""))
                                     ^
/usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-html-matchers-0.7.3/lib/rspec-html-matchers.rb:393: dynamic constant assignment
  DATE_FIELD_TYPES = %w( date month week time date...
                    ^
/usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-html-matchers-0.7.3/lib/rspec-html-matchers.rb:566: syntax error, unexpected $end, expecting kEND
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `require'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
        from /vagrant/config/application.rb:10
        from /vagrant/config/environment.rb:3:in `require'
        from /vagrant/config/environment.rb:3
        from /vagrant/spec/spec_helper.rb:6:in `require'
        from /vagrant/spec/spec_helper.rb:6
        from /vagrant/spec/config/initializers/active_record_spec.rb:2:in `require'
        from /vagrant/spec/config/initializers/active_record_spec.rb:2
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load_spec_files'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/rspec-core-3.5.4/exe/rspec:4
        from /usr/local/rbenv/versions/1.8.7/bin/rspec:19:in `load'
        from /usr/local/rbenv/versions/1.8.7/bin/rspec:19
```

**Comment by kucaahbe** [comment]
@hiteshsharma looks like you ruby version is `1.8.7-p374`, which is definitely not supported

**Comment by kucaahbe** [comment]
recent versions (> 0.9.1) has ruby 1.8 support
